In [1]:
import numpy as np

## Part 1

In [2]:
initial_grid = """
...#..#.
#..#...#
.....###
##....##
......##
........
.#......
##...#..
""".strip().replace(".", "0").replace("#", "1")

In [3]:
int_list = []

for row in initial_grid.split("\n"):
    
    int_list.append([int(e) for e in list(row)])

In [4]:
start = np.asarray(int_list)

In [5]:
start.shape

(8, 8)

In [6]:
start.dtype

dtype('int64')

In [7]:
start

array([[0, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0]])

In [8]:
grid = np.empty((30, 30, 20), dtype="int64")

In [9]:
grid.shape

(30, 30, 20)

In [10]:
grid[
    int((grid.shape[1] / 2) - 4) : int((grid.shape[0] / 2) + 4),
    int((grid.shape[1] / 2) - 4) : int((grid.shape[0] / 2) + 4),
    int(grid.shape[2] / 2),
] = start

grid[
    int((grid.shape[1] / 2) - 4) : int((grid.shape[0] / 2) + 4),
    int((grid.shape[1] / 2) - 4) : int((grid.shape[0] / 2) + 4),
    int(grid.shape[2] / 2),
] = start

In [11]:
# grid[11:19, 11:19, 10] == start

In [12]:
(grid.shape[0]/2) + 4, (grid.shape[1]/2) - 4

(19.0, 11.0)

In [13]:
def nn(grid, coord: tuple, dist: int = 1):

    res = []

    x = coord[0]
    x_lo = x - dist if x - dist >= 0 else 0
    x_hi = x + dist if x + dist <= grid.shape[0] - 1 else grid.shape[0] - 1

    y = coord[1]
    y_lo = y - dist if y - dist >= 0 else 0
    y_hi = y + dist if y + dist <= grid.shape[1] - 1 else grid.shape[1] - 1

    z = coord[2]
    z_lo = z - dist if z - dist >= 0 else 0
    z_hi = z + dist if z + dist <= grid.shape[2] - 1 else grid.shape[2] - 1

    for xx in set([x, x_hi, x_lo]):
        for yy in set([y, y_hi, y_lo]):
            for zz in set([z, z_hi, z_lo]):
                res.append(grid[xx, yy, zz])

    res.remove(grid[x, y, z])

    return np.asarray(res)

In [14]:
nn(grid, (0,1,2))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
def get_counts(arr):

    unique_counts = np.unique(arr, return_counts=True)

    return dict(
        zip(
            unique_counts[0],
            unique_counts[1],
        )
    )

In [16]:
get_counts(nn(grid, (11,18,10)))

{0: 24, 1: 2}

* If a cube is **active** and *exactly 2 or 3 of its neighbors* are *also active*, the cube *remains active*. Otherwise, the cube *becomes inactive*.

* If a cube is **inactive** but *exactly 3* of its neighbors are *active*, the cube *becomes active*. Otherwise, the cube *remains inactive*.

In [18]:
from tqdm import tqdm

In [19]:
state_1 = grid.copy()
state_2 = np.empty_like(state_1)

# it = np.nditer(state_1, flags=["multi_index"])


for l in range(6):

    print(l)

    it = np.nditer(state_1, flags=["multi_index"])

    for x in tqdm(it):

        # print(f"Value:{x} Index:{it.multi_index}")

        cell_value = x

        current_idx = it.multi_index

        neighbours = nn(state_1, current_idx)

        cts = get_counts(neighbours)

        if cell_value == 1:
            if (1 in cts) and (cts[1] in {2, 3}):
                state_2[current_idx] = 1
            else:
                state_2[current_idx] = 0

        elif cell_value == 0:
            if (1 in cts) and (cts[1] == 3):
                state_2[current_idx] = 1
            else:
                state_2[current_idx] = 0

        else:
            raise ValueError(f"Incorrec cell value {cell_value}")

    state_1 = state_2.copy()
    state_2 = np.empty_like(state_1)
    it = np.nditer(state_1, flags=["multi_index"])

0


18000it [00:04, 3746.48it/s]         
356it [00:00, 3556.52it/s]           

1


18000it [00:03, 4755.52it/s]
650it [00:00, 6496.49it/s]           

2


18000it [00:02, 6192.46it/s]
251it [00:00, 1930.43it/s]           

3


18000it [00:03, 5829.85it/s]
694it [00:00, 6937.16it/s]           

4


18000it [00:02, 6414.19it/s]
715it [00:00, 7112.45it/s]           

5


18000it [00:02, 6093.34it/s]


In [20]:
# np.equal(state_2, state_1)

In [21]:
np.unique(state_1, return_counts=True)

(array([0, 1]), array([17760,   240]))

## Part 2

In [1]:
import numpy as np

In [2]:
initial_grid = """
...#..#.
#..#...#
.....###
##....##
......##
........
.#......
##...#..
""".strip().replace(".", "0").replace("#", "1")

In [3]:
int_list = []

for row in initial_grid.split("\n"):
    
    int_list.append([int(e) for e in list(row)])

In [4]:
start = np.asarray(int_list)

In [5]:
start.shape

(8, 8)

In [7]:
start.dtype

dtype('int64')

In [8]:
start

array([[0, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0]])

In [9]:
grid = np.zeros((22, 22, 14, 14), dtype="int64")

In [10]:
grid.shape[3]

14

In [11]:
grid[
    int((grid.shape[1] / 2) - 4) : int((grid.shape[0] / 2) + 4),
    int((grid.shape[1] / 2) - 4) : int((grid.shape[0] / 2) + 4),
    int(grid.shape[2] / 2),
    int(grid.shape[3] / 2),
] = start

In [12]:
np.unique(grid, return_counts=True)

(array([0, 1]), array([94846,    18]))

In [13]:
int((grid.shape[1] / 2) - 4)

7

In [16]:
def nn(grid, coord: tuple, dist: int = 1):

    res = []

    x = coord[0]
    x_lo = x - dist if x - dist >= 0 else 0
    x_hi = x + dist if x + dist <= grid.shape[0] - 1 else grid.shape[0] - 1

    y = coord[1]
    y_lo = y - dist if y - dist >= 0 else 0
    y_hi = y + dist if y + dist <= grid.shape[1] - 1 else grid.shape[1] - 1

    z = coord[2]
    z_lo = z - dist if z - dist >= 0 else 0
    z_hi = z + dist if z + dist <= grid.shape[2] - 1 else grid.shape[2] - 1
    
    w = coord[3]
    w_lo = w - dist if w - dist >= 0 else 0
    w_hi = w + dist if w + dist <= grid.shape[3] - 1 else grid.shape[3] - 1

    for xx in set([x, x_hi, x_lo]):
        for yy in set([y, y_hi, y_lo]):
            for zz in set([z, z_hi, z_lo]):
                for ww in set([w, w_hi, w_lo]):
                    res.append(grid[xx, yy, zz, ww])

    res.remove(grid[x, y, z, w])

    return np.asarray(res)

In [17]:
nn(grid, (0,1,2,2))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
def get_counts(arr):

    unique_counts = np.unique(arr, return_counts=True)

    return dict(
        zip(
            unique_counts[0],
            unique_counts[1],
        )
    )

In [19]:
get_counts(nn(grid, (7, 7, 3, 3)))

{0: 80}

* If a cube is **active** and *exactly 2 or 3 of its neighbors* are *also active*, the cube *remains active*. Otherwise, the cube *becomes inactive*.

* If a cube is **inactive** but *exactly 3* of its neighbors are *active*, the cube *becomes active*. Otherwise, the cube *remains inactive*.

In [20]:
from tqdm import tqdm

In [21]:
state_1 = grid.copy()
state_2 = np.empty_like(state_1)

# it = np.nditer(state_1, flags=["multi_index"])


for l in range(6):

    print(l)

    it = np.nditer(state_1, flags=["multi_index"])

    for x in tqdm(it):

        # print(f"Value:{x} Index:{it.multi_index}")

        cell_value = x

        current_idx = it.multi_index

        neighbours = nn(state_1, current_idx)

        cts = get_counts(neighbours)

        if cell_value == 1:
            if (1 in cts) and (cts[1] in {2, 3}):
                state_2[current_idx] = 1
            else:
                state_2[current_idx] = 0

        elif cell_value == 0:
            if (1 in cts) and (cts[1] == 3):
                state_2[current_idx] = 1
            else:
                state_2[current_idx] = 0

        else:
            raise ValueError(f"Incorrec cell value {cell_value}")

    state_1 = state_2.copy()
    state_2 = np.empty_like(state_1)
    it = np.nditer(state_1, flags=["multi_index"])

114it [00:00, 1136.38it/s]           

0


94864it [00:18, 5071.55it/s]
982it [00:00, 9814.30it/s]           

1


94864it [00:14, 6524.59it/s]
877it [00:00, 8768.77it/s]           

2


94864it [00:14, 6520.27it/s]
792it [00:00, 7904.65it/s]           

3


94864it [00:13, 6894.87it/s]
2027it [00:00, 10054.15it/s]         

4


94864it [00:13, 7251.90it/s]
1621it [00:00, 7595.81it/s]          

5


94864it [00:14, 6739.37it/s]


In [23]:
np.unique(state_1, return_counts=True)

(array([0, 1]), array([93684,  1180]))